export const transactionData = [
  {
    date: "01 May 2021",
    email: "gani@email.com",
    amount: "NGN 25,000",
    channel: "Bank account",
    reference: "yu89a657yht",
    status: "Processing",
  },
  {
    date: "09 Oct 2020",
    email: "tife.balo@email.com",
    amount: "NGN 5,000",
    channel: "Bank transfer",
    reference: "00hpbna711x",
    status: "Processing",
  },
  {
    date: "10 Feb 2020",
    email: "momoyin@email.com",
    amount: "NGN 10,000",
    channel: "Card payment",
    reference: "gt787pma21i",
    status: "Declined",
  },
  {
    date: "27 Jun 2021",
    email: "usman.yakubu@email.com",
    amount: "NGN 15,000",
    channel: "Bank transfer",
    reference: "87udb56troy",
    status: "Completed",
  },
  {
    date: "19 Apr 2021",
    email: "ayo.ola@email.com",
    amount: "NGN 6,000",
    channel: "Card payment",
    reference: "xc77ll01qwy",
    status: "Completed",
  },
  {
    date: "05 Jun 2021",
    email: "ubahbenita@email.com",
    amount: "NGN 4,500",
    channel: "USSD",
    reference: "09tkma3yu6t",
    status: "Completed",
  },
  {
    date: "26 Oct 2020",
    email: "nikeoni@email.com",
    amount: "NGN 8,000",
    channel: "Bank account",
    reference: "ob980yu7asd",
    status: "Declined",
  },
  {
    date: "23 Mar 2020",
    email: "oluchi.uzo@email.com",
    amount: "NGN 3,000",
    channel: "Card payment",
    reference: "pp12xcgh45y",
    status: "Completed",
  },
  {
    date: "17 Oct 2021",
    email: "mo.yusuf@email.com",
    amount: "NGN 9,000",
    channel: "QR code",
    reference: "ke789dgi870",
    status: "Completed",
  },
  {
    date: "09 Jun 2021",
    email: "emma.fayemi@email.com",
    amount: "NGN 20,000",
    channel: "Card payment",
    reference: "wkd342rus65",
    status: "Completed",
  },
];
