export interface Order {
  total: number;
  id: number;
  dateCreated: string;
  paymentReference: string;
  orderReference: string;
  subsidiaryId: number;
  subsidiaryName: string;
  customerId: number;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  accountNumber: string;
  cardType: string;
  maskedPan: string;
  ipAddress: string;
  amount: number;
  amountFormatted: string;
  orderStatus: string;
  currency: string;
  paymentType: string;
  paymentResponseCode: string;
  paymentResponseMessage: string;
  narration: string;
  externalReference: string;
  remarks: string;
  whoBearsFee: string;
  settlementStatus: string;
  settlementAmount: number;
  settlementAmountFormatted: string | null;
  fee: number;
  feeFormatted: string;
  subsidiaryFee: number;
  subsidiaryFeeFormatted: string | null;
  customerFee: number | null;
  customFeeFormatted: string | null;
  dateUpdated: string;
  datePaymentConfirmed: string;
  appEnvironmentId: number;
  appEnvironment: string | null;
  orderPaymentId: number;
  orderPaymentReference: string;
  paymentTypeName: string;
  processorProviderBank: string;
  processorProviderUsername: string;
  finalSettlementDate: string;
  initialSettlementDate: string;
  paymentLinkId: number | null;
  paymentLinkReference: string | null;
  recurringPaymentId: number | null;
  recurringPaymentReference: string | null;
}
